export { default as AdminLayout } from "./AdminLayout";
export { default as Dashboard } from "./Dashboard";
export { default as ManageOrder } from "./ManageOrder";
export { default as ManageProducts } from "./ManageProducts";
export { default as ManageCategory } from "./ManageCategory";
export { default as ManageUser } from "./ManageUser";
export { default as CreateProducts } from "./CreateProducts";
export { default as CreateCategorys } from "./CreateCategorys";
// export { default as ManageCategorys } from "./ManageCategorys";
export { default as UpdateProduct } from "./UpdateProduct";
export { default as UpdateCategory } from "./UpdateCategory";
